### ISSUE TITLE
download templates manually

### ISSUE THREAD

**Issue by danazor** [WubbaLubbaDubDubDev/notpixel_bot_advanced#11]
I know I can't download all the templates but is there a way to download templates manually? Sometimes it's very difficult to switch to a new map. Maybe there's a way to shorten this time

By the way, when I set the less painted templates option to "false", it gives an error 500.

![02c228aa-24e7-4a6d-9dac-1b3aec6ba8e8](https://github.com/user-attachments/assets/67e9d4e4-4cd7-4836-847e-bbe1300e9391)

**Comment by WubbaLubbaDubDubDev** [comment]
> I know I can't download all the templates but is there a way to download templates manually? Sometimes it's very difficult to switch to a new map. Maybe there's a way to shorten this time
> 
> By the way, when I set the less painted templates option to "false", it gives an error 500.
> 

I've reworked the image loader to use the requests library since the aiohttp implementation wasn't working properly when proxies were used, causing image loading to break. Can't say for sure what's causing this behavior yet - maybe I'm missing something or don't fully understand something. In any case, the new implementation works in principle, and during my testing no exceptions occurred, so hopefully there will be minimal issues. Regarding your suggestion about manual template installation - i think I'll add this functionality in the next update.
