### ISSUE TITLE
420_FLOOD_WAIT_x error

### ISSUE THREAD

**Issue by danazor** [WubbaLubbaDubDubDev/notpixel_bot_advanced#13]
Hello @WubbaLubbaDubDubDev  I started getting this error on my accounts for a few days. The situation is the same on accounts where I use a proxy and those where I don't.

After getting the error, I restart the bot. After doing this 3-4 times, the bot starts working normally.

Also I created new sessions and tested it, but the situation still didn't change.

![27ca05bc-03a1-4dbf-ab80-683b6a95ca59](https://github.com/user-attachments/assets/c993ac54-63e6-4807-93b0-9475e4cab085)

**Comment by WubbaLubbaDubDubDev** [comment]
> Hello @WubbaLubbaDubDubDev  I started getting this error on my accounts for a few days. The situation is the same on accounts where I use a proxy and those where I don't.
> 
> After getting the error, I restart the bot. After doing this 3-4 times, the bot starts working normally.
> 
> Also I created new sessions and tested it, but the situation still didn't change.
> 
Hi.

This issue is due to a rate limit imposed by the Telegram API, requiring a wait time before the next request can be made. I’ll look into ways to address this and will add a fix soon.

**Comment by WubbaLubbaDubDubDev** [comment]
> Hello @WubbaLubbaDubDubDev I started getting this error on my accounts for a few days. The situation is the same on accounts where I use a proxy and those where I don't.
> 
> After getting the error, I restart the bot. After doing this 3-4 times, the bot starts working normally.
> 
> Also I created new sessions and tested it, but the situation still didn't change.
> 
I’ve added handling for this error in the latest update. Now, the bot will sleep for the time specified by Telegram when it encounters this rate limit. This is a restriction imposed by Telegram for new users, introduced recently. For now, this is the solution I recommend. This issue is currently affecting all scripts.

**Comment by danazor** [comment]
I downloaded the latest version of the bot and started testing it. There are currently 3 accounts connected to 1 API. Two of them started working without any problems, the other one gave an error and went to sleep. By the way, the account that gave the error is about 1 year old. I will test it for a few more hours and let you know the result.

Thanks

**Comment by WubbaLubbaDubDubDev** [comment]
> I downloaded the latest version of the bot and started testing it. There are currently 3 accounts connected to 1 API. Two of them started working without any problems, the other one gave an error and went to sleep. By the way, the account that gave the error is about 1 year old. I will test it for a few more hours and let you know the result.
> 
> Thanks

Regarding restrictions for new users, this is, of course, just an assumption based on the fact that older accounts typically do not encounter such errors, according to reports from other users. There may be other factors influencing this situation.

I would also like to clarify: is the API registered on a new or old account? And are the same APIs and proxies used in other bots, possibly for other games? This will help gather more details about the environment in which this error occurs.

**Comment by AKASH-UWU** [comment]
I haven't tried it yet, but I also noticed this error. Is it working now?
![image](https://github.com/user-attachments/assets/dac29887-822a-4951-9110-b92303e41b1b)

**Comment by WubbaLubbaDubDubDev** [comment]
> I haven't tried it yet, but I also noticed this error. Is it working now?
> ![image](https://github.com/user-attachments/assets/dac29887-822a-4951-9110-b92303e41b1b)
> 

Hello! Could you please specify the conditions under which this error occurs? How frequently do you encounter it, and when exactly does it happen? Additionally, it would be helpful if you could provide a bit more log information; that would make it easier for me to identify the issue and work on a solution. Thank you!

**Comment by AKASH-UWU** [comment]
The flood errors and invalid peer ID issues seem to start only after 8 or 9 a.m., while everything runs smoothly during the night (after 3 am to 8am). Btw I am still using previous version.


![image](https://github.com/user-attachments/assets/72ab7034-c15f-451d-bad0-94356f427f5a)

**Comment by WubbaLubbaDubDubDev** [comment]
> The flood errors and invalid peer ID issues seem to start only after 8 or 9 a.m., while everything runs smoothly during the night (after 3 am to 8am). Btw I am still using previous version.
> 
> 
> ![image](https://github.com/user-attachments/assets/72ab7034-c15f-451d-bad0-94356f427f5a)

Alright, I'll look into this issue

**Comment by WubbaLubbaDubDubDev** [comment]
> The flood errors and invalid peer ID issues seem to start only after 8 or 9 a.m., while everything runs smoothly during the night (after 3 am to 8am). Btw I am still using previous version.
> 
> 
> ![image](https://github.com/user-attachments/assets/72ab7034-c15f-451d-bad0-94356f427f5a)

It seems that the issue is almost resolved 🫡. After exiting sleep mode, the peer_id becomes invalid. This means that re-authorization is necessary. I will release an update tomorrow. Thank you for the detailed log

**Comment by WubbaLubbaDubDubDev** [comment]
@AKASH-UWU 
Hi! The issue has been fixed. Please check if it's working correctly now. If you encounter any further problems, feel free to let me know. Thanks!

**Comment by AKASH-UWU** [comment]
Alright, I’m using the latest updated code now. Let’s see how it goes—I’ll let you know if there are any issues.

**Comment by WubbaLubbaDubDubDev** [comment]
> It seems the error still exists and occurs after joining a squad (though I’m not sure). Maybe the session is getting closed after joining can you check?

No, that situation is unlikely, as a new authorization is performed specifically for joining a squad, independently of the main session. Joining is handled by a separate bot, notgames_bot. I believe the issue lies in the function responsible for joining the clan, which comes from the original code that I forked. It doesn’t handle cases where obtaining the bearer_token fails—something that could happen due to server overload, connection issues, etc. Instead, it simply throws an error. I’m currently working on improving this function to implement retries for obtaining the token.

**Comment by WubbaLubbaDubDubDev** [comment]
> It seems the error still exists and occurs after joining a squad (though I’m not sure). Maybe the session is getting closed after joining can you check?

Yes, you’re right. I tried replicating the scenario by joining a squad, and on the third attempt, when joining happened before other actions, I encountered the situation where the session closed right afterward. The issue was due to the ```with``` block, which automatically closes the connection upon exit. I should either create a new connection specifically for this function (since joining the squad is handled by a different bot) or remove the ```with``` block and instead pass the main session, which closes within the join_squad function. This causes all actions attempted after joining the squad to throw an error due to a closed session.

It seems I overlooked this function when I implemented the action sequence randomization. In the original code (which I forked), as well as previous versions of my fork, this function was executed last, which avoided any issues. And since all my accounts were already in a squad, I hadn’t noticed the problem. Thanks for pointing it out!

**Comment by WubbaLubbaDubDubDev** [comment]
@AKASH-UWU 
I’ve made some adjustments to the script; everything should now work properly. The main session remains active after joining a squad. Please update and check to confirm. If you encounter any issues, don’t hesitate to let me know right away!

**Comment by AKASH-UWU** [comment]
Alright testing it out now!

**Comment by AKASH-UWU** [comment]
It seems to show up after the painting  is completed and goes to sleep

**Comment by WubbaLubbaDubDubDev** [comment]
> ~~It seems to show up after the painting  is completed and goes to sleep..~~
> 
> ~~Wait seems like i was using the previous code lemme try with your latest one without proxy.~~
> 
> 
> I solved the problem ✅

Glad to hear the problem was solved! Could you share some details about what caused the issue? It might help someone in the future

**Comment by AKASH-UWU** [comment]
Just removed the account which was suspicious of causing problems and it started working again.
