### ISSUE TITLE
canvas loading error

### ISSUE THREAD

**Issue by SeiZ28** [WubbaLubbaDubDubDev/notpixel_bot_advanced#14]
![image](https://github.com/user-attachments/assets/c748a805-9ddd-4d43-a53b-1761bcdfe5c6)
why my canvas is not loading?

**Comment by WubbaLubbaDubDubDev** [comment]
>  why my canvas is not loading?


It seems the issue is on NotPixel's side — error 404 might indicate a problem accessing the data or an SSL error. Everything is working flawlessly for me at the moment. Are you using a proxy?

**Comment by WubbaLubbaDubDubDev** [comment]
> ![image](https://github.com/user-attachments/assets/c748a805-9ddd-4d43-a53b-1761bcdfe5c6)
> why my canvas is not loading?

I thought about what could be causing this behavior. Perhaps you don’t have a template selected, so when we try to request your template, we get a 404 error because you don’t have one. Try manually selecting a template in the application; this should help if I understood the source of the problem correctly.

**Comment by WubbaLubbaDubDubDev** [comment]
It seems that this is indeed a limitation of the script. The issue is that before subscribing to a new, randomly selected template, it requests the current one, compares their IDs, and if they don’t match, it makes a subscription request for the new template. This mechanism prevents unnecessary subscription requests for templates you are already subscribed to. However, since it requires retrieving the old template, if you haven’t subscribed to any templates before or if it has been deleted, situations may arise where the script tries to retrieve a template that you don’t have or that has been removed.

I will add a fix in the next update, but for now, you can try manually subscribing to a template first.
