### ISSUE TITLE
not working without a proxy 

### ISSUE THREAD

**Issue by itsAmiraly** [WubbaLubbaDubDubDev/notpixel_bot_advanced#2]
Input the proxy in the format type://user:pass@ip:port (press Enter to use without proxy):
NotPixel | 2024-10-14 12:21:03 | ERROR    | 13 - Error occurred: Unsupported proxy format:

**Comment by WubbaLubbaDubDubDev** [comment]
Everything works fine, I checked it. However, you may encounter this issue for the following reasons:

1. Incorrect proxy format. Make sure it's in the form: http://username:password@192.168.0.1:8080
2. Using a hostname instead of an IP address. The proxy should contain an IP address, not a domain name. For example, http://username:password@dataimpulse.com:8080 will not work

Please check and let me know once you've verified it.

**Comment by WubbaLubbaDubDubDev** [comment]
> Input the proxy in the format type://user:pass@ip:port (press Enter to use without proxy): NotPixel | 2024-10-14 12:21:03 | ERROR | 13 - Error occurred: Unsupported proxy format:

I apologize for the misunderstanding; I didn't realize right away what the issue was. I forgot to add a check for the presence of a bound proxy to the session. This problem has been fixed now. Thank you for your patience!
