### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ibrahimonay** [WubbaLubbaDubDubDev/notpixel_bot_advanced#8]
![Ekran görüntüsü 2024-10-24 164523](https://github.com/user-attachments/assets/ec582b5a-d28f-418a-8f1c-d7d0c87bca03)

It does not paint. Could you help me ?

**Comment by WubbaLubbaDubDubDev** [comment]
> It does not paint. Could you help me ?

That's strange. According to the log, it looks like the download_image function wasn't called with await. However, I checked, and the await is in place. Try downloading the bot again; you might have an outdated version of tapper.py.

I also see that the canvas isn't loading for you, which usually happens due to connection issues or problems with the proxy.

**Comment by WubbaLubbaDubDubDev** [comment]
> It does not paint. Could you help me ?

Please let me know if the issue is not resolved.
